import { cardText } from "./card-text.js";
import { ACTOR_INKS } from "./actor-ink.js";
export const HEROES = [
  {
    id: "kael",
    name: "凯尔",
    title: "烬火剑士",
    color: ACTOR_INKS.kael,
    icon: "sword",
    team: "ally",
    hp: 1,
  },
  {
    id: "lyra",
    name: "莉娅",
    title: "星潮术师",
    color: ACTOR_INKS.lyra,
    icon: "star",
    team: "ally",
    hp: 1,
  },
  {
    id: "syl",
    name: "希尔",
    title: "逐风游侠",
    color: ACTOR_INKS.syl,
    icon: "bow",
    team: "ally",
    hp: 1,
  },
];
export const MODELS = [
  ...HEROES,
  {
    id: "shard",
    name: "晶棘哨卫",
    color: ACTOR_INKS.shard,
    icon: "diamond",
    team: "enemy",
    hp: 1,
  },
  {
    id: "warden",
    name: "荒星守望者",
    color: ACTOR_INKS.warden,
    icon: "crown",
    team: "enemy",
    hp: 1,
  },
  {
    id: "wisp",
    name: "虚空游灵",
    color: ACTOR_INKS.wisp,
    icon: "diamond",
    team: "enemy",
    hp: 1,
  },
];
export const CARDS = {
  strike: {
    name: "烬刃",
    hero: "kael",
    type: "attack",
    cost: 1,
    damage: 6,
    upDamage: 3,
    icon: "sword",
    rarity: "基础",
    text: "造成 {damage} 点伤害。",
  },
  guard: {
    name: "星幕",
    hero: "lyra",
    type: "skill",
    cost: 1,
    block: 5,
    upBlock: 3,
    icon: "shield",
    rarity: "基础",
    text: "获得 {block} 点格挡。",
  },
  quick: {
    name: "掠风",
    hero: "syl",
    type: "attack",
    cost: 0,
    damage: 4,
    upDamage: 3,
    draw: 1,
    icon: "bow",
    rarity: "基础",
    text: "造成 {damage} 点伤害。抽 1 张牌。消耗。",
    exhaust: true,
  },
  brand: {
    name: "破晓烙印",
    hero: "kael",
    type: "attack",
    cost: 2,
    damage: 8,
    upDamage: 3,
    vulnerable: 2,
    icon: "diamond",
    rarity: "进阶",
    text: "造成 {damage} 点伤害。施加 2 回合易伤：受到攻击伤害 +50%。",
  },
  foresight: {
    name: "星流预见",
    hero: "lyra",
    type: "skill",
    cost: 0,
    draw: 2,
    upDraw: 1,
    icon: "eye",
    rarity: "进阶",
    text: "抽 {draw} 张牌。消耗。",
    exhaust: true,
  },
  parry: {
    name: "回风架势",
    hero: "syl",
    type: "skill",
    cost: 1,
    block: 8,
    upBlock: 4,
    nextAttack: 5,
    icon: "shield",
    rarity: "进阶",
    text: "获得 {block} 格挡。本回合下一张攻击牌伤害 +5。",
  },
  finisher: {
    name: "落日裁决",
    hero: "kael",
    type: "attack",
    cost: 2,
    damage: 12,
    upDamage: 6,
    finisher: 4,
    icon: "crown",
    rarity: "稀有",
    text: "造成 {damage} 伤害。本回合此前每打出一张攻击牌，伤害再 +4。",
    cinematic: true,
  },
  ember: {
    name: "余烬风暴",
    hero: "kael",
    type: "attack",
    cost: 1,
    damage: 5,
    upDamage: 3,
    burn: 4,
    icon: "bolt",
    rarity: "进阶",
    text: "造成 {damage} 伤害，施加 4 燃烧。燃烧在敌方行动前扣血，然后减 1。",
  },
  detonate: {
    name: "焚星引爆",
    hero: "kael",
    type: "attack",
    cost: 1,
    damage: 6,
    upDamage: 4,
    detonate: 3,
    icon: "spark",
    rarity: "稀有",
    text: "造成 {damage} 伤害，消耗目标全部燃烧，每层额外造成 3 点伤害。",
    cinematic: true,
  },
  volley: {
    name: "千羽齐射",
    hero: "syl",
    type: "attack",
    cost: 1,
    damage: 4,
    upDamage: 2,
    hits: 3,
    icon: "bow",
    rarity: "进阶",
    text: "造成 {damage} 伤害，连续攻击 3 次。力量对每次命中生效。",
  },
  meteor: {
    name: "天陨 · 终焰",
    hero: "kael",
    type: "attack",
    cost: 3,
    damage: 32,
    upDamage: 12,
    all: true,
    exhaust: true,
    icon: "spark",
    rarity: "传说",
    text: "对所有敌人造成 {damage} 伤害。消耗。",
    cinematic: true,
  },
  nova: {
    name: "星界坍缩",
    hero: "lyra",
    type: "attack",
    cost: 2,
    damage: 13,
    upDamage: 6,
    all: true,
    weak: 1,
    icon: "star",
    rarity: "稀有",
    text: "对所有敌人造成 {damage} 伤害，施加 1 回合虚弱：攻击伤害 −25%。",
    cinematic: true,
  },
  mend: {
    name: "星泉祷言",
    hero: "lyra",
    type: "skill",
    cost: 1,
    heal: 6,
    upHeal: 4,
    block: 5,
    upBlock: 3,
    exhaust: true,
    icon: "leaf",
    rarity: "进阶",
    text: "恢复 {heal} 生命，获得 {block} 格挡。消耗。",
  },
  focus: {
    name: "超频",
    hero: "lyra",
    type: "skill",
    cost: 0,
    energy: 1,
    upEnergy: 1,
    exhaust: true,
    icon: "bolt",
    rarity: "进阶",
    text: "获得 {energy} 能量。消耗。",
  },
  strength: {
    name: "燃魂",
    hero: "kael",
    type: "power",
    cost: 1,
    strength: 2,
    upStrength: 1,
    icon: "sword",
    rarity: "稀有",
    text: "本场战斗获得 {strength} 力量：每次攻击伤害增加等量数值。",
  },
  afterimage: {
    name: "风之残像",
    hero: "syl",
    type: "power",
    cost: 1,
    afterimage: 3,
    upAfterimage: 2,
    icon: "leaf",
    rarity: "稀有",
    text: "本场战斗每打出一张攻击牌，获得 {afterimage} 格挡。",
  },
  fortress: {
    name: "不坠星城",
    hero: "lyra",
    type: "skill",
    cost: 2,
    block: 19,
    upBlock: 9,
    icon: "shield",
    rarity: "进阶",
    text: "获得 {block} 格挡。",
  },
  pierce: {
    name: "贯星箭",
    hero: "syl",
    type: "attack",
    cost: 1,
    damage: 10,
    upDamage: 5,
    pierce: true,
    icon: "bow",
    rarity: "进阶",
    text: "造成 {damage} 伤害，无视敌人格挡。",
  },
  siphon: {
    name: "星火汲取",
    hero: "kael",
    type: "attack",
    cost: 1,
    damage: 8,
    upDamage: 4,
    onKillEnergy: 2,
    icon: "bolt",
    rarity: "进阶",
    text: "造成 {damage} 伤害。击杀目标时获得 2 能量。",
  },
  frost: {
    name: "寂静轨道",
    hero: "lyra",
    type: "skill",
    cost: 1,
    weak: 2,
    vulnerable: 1,
    target: true,
    icon: "diamond",
    rarity: "进阶",
    text: "施加 2 回合虚弱与 1 回合易伤。升级后费用降至 0。",
    upCost: 0,
  },
  echo: {
    name: "回响斩",
    hero: "syl",
    type: "attack",
    cost: 1,
    damage: 6,
    upDamage: 3,
    draw: 1,
    icon: "sword",
    rarity: "进阶",
    text: "造成 {damage} 伤害。抽 1 张牌。",
  },
  wound: {
    name: "裂隙创伤",
    hero: "kael",
    type: "curse",
    cost: 99,
    icon: "cross",
    rarity: "诅咒",
    text: "无法打出。占据抽牌位置，可在商店移除。",
  },
};
export const RELICS = {
  emberheart: {
    name: "余烬之心",
    icon: "bolt",
    starter: true,
    text: "战斗胜利时恢复 6 生命。",
  },
  starcore: {
    name: "星潮核心",
    icon: "star",
    starter: true,
    text: "每回合首次打出技能牌，抽 1 张牌。",
  },
  quiver: {
    name: "逐风箭匣",
    icon: "bow",
    starter: true,
    text: "每回合每打出 3 张攻击牌，获得 5 格挡。",
  },
  prism: {
    name: "三相星棱",
    icon: "spark",
    text: "每回合每打出 3 张牌，回 1 能量、抽 1 张牌。每回合最多 2 次。",
  },
  shell: {
    name: "旧王护符",
    icon: "shield",
    text: "每场战斗开始时获得 10 格挡。",
  },
  candle: { name: "不熄灯芯", icon: "bolt", text: "施加燃烧时额外增加 2 层。" },
  fang: {
    name: "风蚀獠牙",
    icon: "sword",
    text: "每场战斗开始时获得 1 力量。",
  },
  mirror: {
    name: "星棱镜片",
    icon: "diamond",
    text: "每回合打出第 3 张牌时，获得 6 格挡。",
  },
  feather: {
    name: "黎明之羽",
    icon: "leaf",
    text: "每次战斗胜利后恢复 5 生命。",
  },
  capacitor: {
    name: "过载核心",
    icon: "star",
    text: "每回合能量 +1，但每回合少抽 1 张牌。",
  },
  purse: {
    name: "拾光者之囊",
    icon: "crown",
    text: "战斗金币奖励增加 20，击杀额外获得 3 金币。",
  },
};
export const CHARACTERS = {
  kael: {
    hp: 80,
    relic: "emberheart",
    art: "blade",
    style: "易伤 · 燃烧 · 终结",
    description: "先暴露弱点，再用重击收割。",
    deck: [
      "strike",
      "strike",
      "strike",
      "strike",
      "strike",
      "kaelGuard",
      "kaelGuard",
      "kaelGuard",
      "kaelGuard",
      "brand",
    ],
  },
  lyra: {
    hp: 70,
    relic: "starcore",
    art: "oracle",
    style: "过牌 · 护盾 · 施法",
    description: "用护盾争取时间，过牌寻找爆发。",
    deck: [
      "sparkshot",
      "sparkshot",
      "sparkshot",
      "sparkshot",
      "guard",
      "guard",
      "guard",
      "guard",
      "foresight",
      "frost",
    ],
  },
  syl: {
    hp: 72,
    relic: "quiver",
    art: "gale",
    style: "连击 · 残像 · 机动",
    description: "串联低费攻击，让每一步攻守兼备。",
    deck: [
      "arrow",
      "arrow",
      "arrow",
      "arrow",
      "sylGuard",
      "sylGuard",
      "sylGuard",
      "sylGuard",
      "quick",
      "parry",
    ],
  },
};
CARDS.kaelGuard = { ...CARDS.guard, name: "铁壁", hero: "kael", block: 5 };
CARDS.sylGuard = { ...CARDS.guard, name: "闪避", hero: "syl", block: 5 };
CARDS.sparkshot = {
  ...CARDS.strike,
  name: "星矢",
  hero: "lyra",
  icon: "star",
  damage: 6,
};
CARDS.arrow = {
  ...CARDS.strike,
  name: "贯风",
  hero: "syl",
  icon: "bow",
  damage: 6,
};
export const FLOORS = [
  [{ type: "battle", name: "浮空圣所", sub: "晶化巡卫 · 初始遭遇" }],
  [
    { type: "event", name: "沉没的星井", sub: "付出代价，交换力量" },
    { type: "battle", name: "断桥守军", sub: "战斗 · 金币与卡牌" },
  ],
  [
    { type: "elite", name: "铁誓看守", sub: "精英 · 遗物奖励" },
    { type: "battle", name: "回声长廊", sub: "战斗 · 稳健前进" },
  ],
  [
    { type: "camp", name: "旅人的篝火", sub: "休息或升级一张牌" },
    { type: "shop", name: "流星集市", sub: "买牌、买遗物、精简牌组" },
  ],
  [
    { type: "battle", name: "碎星前庭", sub: "三名晶化造物" },
    { type: "elite", name: "裂隙执刑者", sub: "精英 · 遗物奖励" },
  ],
  [
    { type: "camp", name: "黎明之前", sub: "最后的休整" },
    { type: "event", name: "无名者遗赠", sub: "力量总有代价" },
  ],
  [{ type: "boss", name: "荒星之巅", sub: "领主 · 荒星守望者" }],
];
export function cardData(card) {
  const base = CARDS[card.key];
  const result = {
    ...base,
    key: card.key,
    uid: card.uid,
    upgraded: !!card.upgraded,
  };
  if (card.upgraded) {
    for (const key of [
      "damage",
      "block",
      "draw",
      "heal",
      "energy",
      "strength",
      "afterimage",
    ])
      result[key] =
        (base[key] || 0) +
        (base["up" + key[0].toUpperCase() + key.slice(1)] || 0);
    if (base.upCost !== undefined) result.cost = base.upCost;
    result.name += "+";
  }
  result.description = cardText(result);
  return result;
}
